# Generated by Django 3.2.4 on 2021-06-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210611_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='discuss',
            field=models.IntegerField(default=0, verbose_name='是否允许别人评论'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display',
            field=models.IntegerField(default=0, verbose_name='是否展示自己的文章'),
        ),
    ]
