# Generated by Django 3.2.4 on 2021-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210615_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display',
        ),
        migrations.AddField(
            model_name='article',
            name='display',
            field=models.BooleanField(default=True, verbose_name='是否展示自己的文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='discuss',
            field=models.BooleanField(default=True, verbose_name='是否允许别人评论'),
        ),
    ]
