# Generated by Django 3.2.4 on 2021-06-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment_user',
        ),
    ]
