# Generated by Django 3.2.4 on 2021-06-16 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_commentreply_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='comment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='被回复人'),
        ),
    ]
