# Generated by Django 3.2.4 on 2021-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_commentreply_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count1',
            field=models.IntegerField(default=0, verbose_name='待处理'),
        ),
    ]
