# Generated by Django 3.2.4 on 2021-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_count1'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='count2',
            field=models.IntegerField(default=0, verbose_name='回复待处理数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='count1',
            field=models.IntegerField(default=0, verbose_name='评论待处理数'),
        ),
    ]
