# Generated by Django 3.2.4 on 2021-06-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210617_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count1',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='count2',
        ),
        migrations.AddField(
            model_name='comment',
            name='undiscuss',
            field=models.BooleanField(default=True, verbose_name='未处理评论'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='unreply',
            field=models.BooleanField(default=True, verbose_name='未处理回复'),
        ),
    ]
